name: Automatisation des tests DevSecOps
on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5

      - name: Dependances
        run: |
          docker run --rm \
            -v "$PWD":/project:ro \
            aquasec/trivy:latest fs \
            --scanners vuln \
            --exit-code 1 \
            --file-patterns 'pip:.*\.txt$' /project

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5

      - name: Test Dockerfile
        run: |
          docker run --rm \
            -v "$PWD":/project:ro \
            aquasec/trivy:latest config \
            --exit-code 1 \
            /project

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
